#!/bin/bash

# Check args
if [ $# -eq 1 ]
  then

  if [ -s /usr/local/pakScripts/$1 ]
  then
     echo "pak | error > $1 already exists"
  else

    # # Check if admin (comment out if you want to disable)
    # if [ "$(id -u)" != "0" ]; then
    #    echo "This script must be run as root" 1>&2
    #    exit 1
    # fi


    touch /usr/local/pakScripts/$1
    echo '#!/bin/bash' >> /usr/local/pakScripts/$1
    echo "# ---- pak builder" >> /usr/local/pakScripts/$1
    echo "# ---- by tyler burnam" >> /usr/local/pakScripts/$1
    echo "" >> /usr/local/pakScripts/$1
    echo "echo hello, $1!" >> /usr/local/pakScripts/$1
    chmod +x /usr/local/pakScripts/$1
    cp /usr/local/pakScripts/$1 /usr/local/bin/
    atom /usr/local/bin/$1:4
  fi
else
  echo "pak | error > enter script name"
fi
